//
//  AlbumWorker.swift
//  DesafioBCI
//
//  Created by Jose on 05-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AlbumWorker {
    func doSomeWork()  {
        
    }
    
    func fetchAlbum(id: Int, completionHandler: @escaping ([AlbumModel]) -> Void) {
        
        ObtenerDatos.instance.getAlbum(id: id) { album in
            completionHandler(album)
        }
        
    }
}
