//
//  AlbumViewController.swift
//  DesafioBCI
//
//  Created by Jose on 05-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumDisplayLogic: class
{
  func displaySomething(viewModel: Album.Something.ViewModel)
}

class AlbumViewController: UIViewController, AlbumDisplayLogic
{
  var interactor: AlbumBusinessLogic?
  var router: (NSObjectProtocol & AlbumRoutingLogic & AlbumDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = AlbumInteractor()
    let presenter = AlbumPresenter()
    let router = AlbumRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    print("Print: \(router?.dataStore?.collectionID ?? 0)")
    
    let navigationBarAppearace = UINavigationBar.appearance()

    navigationBarAppearace.tintColor = .green
    
    
    
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Album.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Album.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
