//
//  AlbumPresenter.swift
//  DesafioBCI
//
//  Created by Jose on 05-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumPresentationLogic
{
  func presentSomething(response: Album.Something.Response)
}

class AlbumPresenter: AlbumPresentationLogic
{
  weak var viewController: AlbumDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Album.Something.Response)
  {
    let viewModel = Album.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
