//
//  BuscarModels.swift
//  DesafioBCI
//
//  Created by Jose on 04-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Buscar {
    // MARK: Use cases
    
    enum Load {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    
    enum Albums {
        struct Request {
            let post: CancionModel
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    
}
