//
//  BuscarPresenter.swift
//  DesafioBCI
//
//  Created by Jose on 04-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuscarPresentationLogic
{
  func presentSomething(response: Buscar.Something.Response)
}

class BuscarPresenter: BuscarPresentationLogic
{
  weak var viewController: BuscarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Buscar.Something.Response)
  {
    let viewModel = Buscar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
