//
//  BuscarInteractor.swift
//  DesafioBCI
//
//  Created by Jose on 04-03-20.
//  Copyright (c) 2020 dev_Jo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuscarBusinessLogic {
    func doLoadInitialData(request: Buscar.Load.Request)
    func doLoadAlbum(request: Buscar.Albums.Request)
}

protocol BuscarDataStore {
    var collectionID: Int { get set }
}

class BuscarInteractor: BuscarBusinessLogic, BuscarDataStore {
    
    
    var presenter: BuscarPresentationLogic?
    var worker: BuscarWorker?
    
    var collectionID: Int = 0
    
    // MARK: Do something
    
    func doLoadInitialData(request: Buscar.Load.Request) {
        worker = BuscarWorker()
        worker?.doSomeWork()
        
        let response = Buscar.Load.Response()
        self.presenter?.presentInitialData(response: response)
        
        
    }
    
    func doLoadAlbum(request: Buscar.Albums.Request) {
        let cancion = request.post
        collectionID = cancion.collectionId
        
        let response = Buscar.Albums.Response()
        
        presenter?.presentAlbums(response: response)
    }
    
    
}
